[package]
name = "dessins"
version = "0.1.0"
authors = ["bikem <bengisuozaydin@gmail.com>"]
edition = "2021"

[lib]
name = "common"
path = "src/lib.rs"

[[bin]]
name = "1-1"
path = "1/1_polygones_reguliers.rs"

[[bin]]
name = "1-2"
path = "1/2_etoiles_regulieres.rs"

[[bin]]
name = "1-3"
path = "1/3_composition_1.rs"

[[bin]]
name = "1-4"
path = "1/4_composition_2.rs"

[[bin]]
name = "1-5"
path = "1/5_joligones.rs"

[[bin]]
name = "2-1-1"
path = "2/1_1_cheval.rs"

[[bin]]
name = "2-1-2"
path = "2/1_2_cheval.rs"

[[bin]]
name = "2-1-3"
path = "2/1_3_cheval.rs"

[[bin]]
name = "2-1-4"
path = "2/1_4_cheval.rs"

[[bin]]
name = "2-1-5"
path = "2/1_5_cheval.rs"

[[bin]]
name = "2-1-6"
path = "2/1_6_cheval.rs"

[[bin]]
name = "2-1-7"
path = "2/1_7_cheval.rs"

[[bin]]
name = "2-1-8"
path = "2/1_8_cheval.rs"

[[bin]]
name = "2-1-9"
path = "2/1_9_cheval.rs"

[[bin]]
name = "2-1-10"
path = "2/1_10_cheval.rs"

[[bin]]
name = "2-2-1-1"
path = "2/2_1_1_lion.rs"

[[bin]]
name = "2-2-1-2"
path = "2/2_1_2_lion.rs"

[[bin]]
name = "2-2-2-1"
path = "2/2_2_1_oiseaux_poissons.rs"

[[bin]]
name = "2-2-2-2"
path = "2/2_2_2_oiseaux_poissons.rs"

[[bin]]
name = "2-2-3-1"
path = "2/2_3_1_smurf.rs"

[[bin]]
name = "2-2-3-2"
path = "2/2_3_2_smurf.rs"

[[bin]]
name = "3-1-1"
path = "3/1_1_dragons.rs"

[[bin]]
name = "3-1-2"
path = "3/1_2_dragons.rs"

[[bin]]
name = "3-1-3"
path = "3/1_3_dragons.rs"

[[bin]]
name = "3-1-4"
path = "3/1_4_dragons.rs"

[[bin]]
name = "3-1-5"
path = "3/1_5_dragons.rs"

[[bin]]
name = "3-1-6"
path = "3/1_6_dragons.rs"

[[bin]]
name = "3-1-7"
path = "3/1_7_dragons.rs"

[[bin]]
name = "4-1"
path = "4/1_etoiles_fractales.rs"

[[bin]]
name = "5-1-1"
path = "5/1_1_courbes_orbitales.rs"

[[bin]]
name = "5-1-2"
path = "5/1_2_courbes_orbitales.rs"

[[bin]]
name = "5-1-3"
path = "5/1_3_courbes_orbitales.rs"

[[bin]]
name = "5-1-4"
path = "5/1_4_courbes_orbitales.rs"

[[bin]]
name = "5-1-5"
path = "5/1_5_courbes_orbitales.rs"

[[bin]]
name = "5-1-6"
path = "5/1_6_courbes_orbitales.rs"

[[bin]]
name = "5-1-7"
path = "5/1_7_courbes_orbitales.rs"

[[bin]]
name = "5-1-8"
path = "5/1_8_courbes_orbitales.rs"

[[bin]]
name = "5-1-9"
path = "5/1_9_courbes_orbitales.rs"

[[bin]]
name = "5-2-1"
path = "5/2_1_courbes_tournantes.rs"

[[bin]]
name = "5-2-2"
path = "5/2_2_courbes_tournantes.rs"

[[bin]]
name = "5-2-3"
path = "5/2_3_courbes_tournantes.rs"

[[bin]]
name = "5-2-4"
path = "5/2_4_courbes_tournantes.rs"

[[bin]]
name = "5-2-5"
path = "5/2_5_courbes_tournantes.rs"

[[bin]]
name = "5-2-6"
path = "5/2_6_courbes_tournantes.rs"

[[bin]]
name = "5-2-7"
path = "5/2_7_courbes_tournantes.rs"

[[bin]]
name = "5-2-8"
path = "5/2_8_courbes_tournantes.rs"

[[bin]]
name = "5-2-9"
path = "5/2_9_courbes_tournantes.rs"

[[bin]]
name = "5-2-10"
path = "5/2_10_courbes_tournantes.rs"

[[bin]]
name = "5-3"
path = "5/3_courbes_spirales.rs"

[[bin]]
name = "6-1"
path = "6/1_biparti_complet.rs"

[dependencies]
evalexpr = "12.0.2"
nannou = "0.19"
nannou_egui = "0.19.0"
