[package]
name = "dessins"
version = "0.1.0"
authors = ["bikem <bengisuozaydin@gmail.com>"]
edition = "2021"

[[bin]]
name = "1-1"
path = "1/1_polygones_reguliers.rs"

[[bin]]
name = "1-2"
path = "1/2_etoiles_regulieres.rs"

[[bin]]
name = "1-3"
path = "1/3_composition_1.rs"

[[bin]]
name = "1-4"
path = "1/4_composition_2.rs"

[[bin]]
name = "1-5"
path = "1/5_joligones.rs"

[[bin]]
name = "2-1-1"
path = "2/1_1_cheval.rs"

[[bin]]
name = "2-1-2"
path = "2/1_2_cheval.rs"

[[bin]]
name = "2-1-3"
path = "2/1_3_cheval.rs"

[[bin]]
name = "2-1-4"
path = "2/1_4_cheval.rs"

[[bin]]
name = "2-1-5"
path = "2/1_5_cheval.rs"

[[bin]]
name = "2-1-6"
path = "2/1_6_cheval.rs"

[[bin]]
name = "2-1-7"
path = "2/1_7_cheval.rs"

[[bin]]
name = "2-1-8"
path = "2/1_8_cheval.rs"

[[bin]]
name = "2-1-9"
path = "2/1_9_cheval.rs"

[[bin]]
name = "2-1-10"
path = "2/1_10_cheval.rs"

[dependencies]
nannou = "0.19"
nannou_egui = "0.19.0"
