[package]
name = "dessins"
version = "0.1.0"
authors = ["bikem <bengisuozaydin@gmail.com>"]
edition = "2021"

[[bin]]
name = "1-1"
path = "1/1_polygones_reguliers.rs"

[[bin]]
name = "1-2"
path = "1/2_etoiles_regulieres.rs"

[dependencies]
nannou = "0.19"
nannou_egui = "0.19.0"
