[workspace]
members = ["crates/dessins", "crates/dessins-lib", "crates/ui-controlled-params"]
resolver = "2"

[workspace.package]
name = "dessins"
authors = ["bikem <bengisuozaydin@gmail.com>"]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
dessins-lib = { path = "crates/dessins-lib", version = "0.1.0" }
ui-controlled-params = { path = "crates/ui-controlled-params", version = "0.1.0" }
evalexpr = "12.0.2"
nannou = "0.19"
nannou_egui = "0.19.0"
quote = "1.0"
syn = { version = "2.0", features = [ "full" ] }
