[package]
name = "ui-controlled-params"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
anyhow.workspace = true
evalexpr.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
