[package]
name = "dessins"
authors.workspace = true
edition.workspace = true
version.workspace = true

[[bin]]
name = "2-1-2"
path = "2/1_2_cheval.rs"

[[bin]]
name = "2-1-3"
path = "2/1_3_cheval.rs"

[[bin]]
name = "2-1-4"
path = "2/1_4_cheval.rs"

[[bin]]
name = "2-1-5"
path = "2/1_5_cheval.rs"

[[bin]]
name = "2-1-6"
path = "2/1_6_cheval.rs"

[[bin]]
name = "2-1-7"
path = "2/1_7_cheval.rs"

[[bin]]
name = "2-1-8"
path = "2/1_8_cheval.rs"

[[bin]]
name = "2-1-9"
path = "2/1_9_cheval.rs"

[[bin]]
name = "2-1-10"
path = "2/1_10_cheval.rs"

[[bin]]
name = "2-2-1-1"
path = "2/2_1_1_lion.rs"

[[bin]]
name = "2-2-1-2"
path = "2/2_1_2_lion.rs"

[[bin]]
name = "2-2-2-1"
path = "2/2_2_1_oiseaux_poissons.rs"

[[bin]]
name = "2-2-2-2"
path = "2/2_2_2_oiseaux_poissons.rs"

[[bin]]
name = "2-2-3-1"
path = "2/2_3_1_smurf.rs"

[[bin]]
name = "2-2-3-2"
path = "2/2_3_2_smurf.rs"

[dependencies]
nannou.workspace = true
dessins-lib.workspace = true
